[tools]
node = "22.11.0"
"npm:prettier" = "3.4.1"
shellcheck = "0.10.0"
shfmt = "3.10.0"
taplo = "0.9.3"
typos = "1.28.1"
"ubi:houseabsolute/omegasort" = "0.1.3"
"ubi:houseabsolute/precious" = "0.9.0"
